### PR TITLE
LPS-115193 As an accounts admin, I want to account to undergo workflow approval process

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-115193](https://issues.liferay.com/browse/LPS-115193).

Hey @RafaelCRC this is not organized, but the idea is here.

### CODE REVIEW

**Comment by erickmonteiroo** [comment]
oh gosh I miss running a `gw buildService`

**Comment by drewbrokke** [comment]
@erickmonteiroo gotta build all those layers by hand now? ;)

**Comment by erickmonteiroo** [comment]
@drewbrokke Unfortunately, yes. On a chaotic and messed code without coding conventions for years hahah

**Comment by drewbrokke** [comment]
Sounds like the Wild West!

**Comment by erickmonteiroo** [comment]
It is!

**Comment by erickmonteiroo** [comment]
@drewbrokke Hah, just received an email about this pr. Good old days of `gw buildService`! Now I sail through Elixir, NodeJs and Java wild waters, all at the same time lol!

**Comment by RafaelCRC** [comment]
wow, what an oldie. Java give me the chills nowadays. i'll stick with nodeJs haha

**Comment by erickmonteiroo** [comment]
@RafaelCRC How dare you 😠! haha

**Comment by drewbrokke** [comment]
@erickmonteiroo how is Elixir? I've heard good things.

**Comment by drewbrokke** [comment]
@RafaelCRC you managed to escape this time, but Java may still be hiding under your bed at night...

**Comment by erickmonteiroo** [comment]
@drewbrokke It's such a powerful language! A weird syntax may I say, but definetely powerful! Needs to take care of where you're going to use it or you may end up using a sledgehammer to crack a nut!

**Pull request closed without merging**
